name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer
          extensions: mbstring, intl, pdo_mysql
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Lint
        run: vendor/bin/php-cs-fixer --version && vendor/bin/php-cs-fixer fix --dry-run --diff || true
      - name: Static Analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist || true
      - name: Run tests
        run: vendor/bin/phpunit --colors=never --display-warnings --do-not-cache-result
